### ISSUE TITLE
Messages.create does not respect partsCount

### ISSUE THREAD

**Issue by davisn** [textmagic/textmagic-rest-python#4]
I'm not sure if this is a problem with the Rest API or the Python client, but when sending a large message (> 160 characters), the message is truncated to one 160-character part.  This is regardless of the whether the `partsCount` parameter is specified, or its value.

For example:
```
>>> t = "Here's a long message that longer than 160 character so it causes the text to be truncated, even though cutExtra and partsCount are set to their default values of false and 6 respectively"
>>> client.messages.create(phones=phones, text=t)
>>> msg = client.messages.create(phones=phones, text=t, partsCount=6)
```

Both `Messages.create` calls above result in a truncated message of one 160-character part.

**Comment by andreylarionov** [comment]
Sending of long messages to the US phone numbers is in development stage. At the moment Textmagic does not provide sending long messages to the USA. Further information about restrictions when sending messages to the USA you can see here: https://support.textmagic.com/article/restrictions-when-sending-messages-to-the-usa-and-canada-via-textmagic/

**Comment by davisn** [comment]
That makes sense, although there is no mention of that in the API documentation.  Also, if `cutExtra` is not set to true, shouldn't the API service reject messages with a payload of more than 160 characters if it can't actually send more than 160 characters?
