### ISSUE TITLE
Implement __iter__ on CollectionModel?

### ISSUE THREAD

**Issue by davisn** [textmagic/textmagic-rest-python#7]
I'm not sure this is a great idea since it could potentially lead to a lot of requests.  However, it would simplify working with collections if `CollectionModel` implemented the `__iter__` magic method by returning a sequence of items from lazy-loaded pages.  For example:

```
def __iter__(self):
    def pages():
        # generator yielding all pages for the resource
    (m for page in pages() for m in page)
```

Perhaps results could be cached to improve performance.

**Comment by andreylarionov** [comment]
Good idea. Perhaps it will be implemented later.
